# Generated by Django 5.1 on 2024-08-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
